### ISSUE TITLE
raspberrypi-firmware soc:firmware: Request

### ISSUE THREAD

**Issue by JLXB** [CodeExecution/Ubuntu-ARM64-RPi#4]
This is a snip from my syslog.  All the messages here repeat fast and continuous.  I am not sure that it is causing any particular problem other then really big log files.  If I open a terminal with Ctl-Alt-F1 through F6, the raspberrypi-firmware message overwrites the terminal screens continuously making the terminal unusable.

The usr/sbin/irqbalance message does not appear anywhere but the syslog.  My syslogs are really big!  Thought I would bring it to your attention.

Jan 11 18:28:55 jlxb kernel: [ 5290.383123] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:28:57 jlxb kernel: [ 5292.399078] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:28:59 jlxb kernel: [ 5294.415118] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:29:01 jlxb kernel: [ 5296.431205] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:29:03 jlxb kernel: [ 5298.447204] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:29:05 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR arch_timer
Jan 11 18:29:05 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR 3f00b880.mailbox
Jan 11 18:29:05 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR doorbell
Jan 11 18:29:05 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR arm-pmu
Jan 11 18:29:05 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR dwc_otg_hcd:usb1
Jan 11 18:29:05 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR dwc_otg_sim-fiq
Jan 11 18:29:05 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR dma
Jan 11 18:29:05 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR IRQ
Jan 11 18:29:05 jlxb /usr/sbin/irqbalance: message repeated 3 times: [ GUESSING AARCH64 CLASS FOR IRQ]
Jan 11 18:29:05 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR bcm2835-auxirq
Jan 11 18:29:05 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR mmc0
Jan 11 18:29:05 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR mmc1
Jan 11 18:29:05 jlxb kernel: [ 5300.463129] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:29:07 jlxb kernel: [ 5302.479145] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:29:09 jlxb kernel: [ 5304.495085] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:29:11 jlxb kernel: [ 5306.511079] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:29:13 jlxb kernel: [ 5308.527107] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:29:15 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR arch_timer
Jan 11 18:29:15 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR 3f00b880.mailbox
Jan 11 18:29:15 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR doorbell
Jan 11 18:29:15 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR arm-pmu
Jan 11 18:29:15 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR dwc_otg_hcd:usb1
Jan 11 18:29:15 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR dwc_otg_sim-fiq
Jan 11 18:29:15 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR dma
Jan 11 18:29:15 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR IRQ
Jan 11 18:29:15 jlxb /usr/sbin/irqbalance: message repeated 3 times: [ GUESSING AARCH64 CLASS FOR IRQ]
Jan 11 18:29:15 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR bcm2835-auxirq
Jan 11 18:29:15 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR mmc0
Jan 11 18:29:15 jlxb /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR mmc1
Jan 11 18:29:15 jlxb kernel: [ 5310.543065] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:29:17 jlxb kernel: [ 5312.559139] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:29:19 jlxb kernel: [ 5314.575105] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:29:21 jlxb kernel: [ 5316.591114] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
Jan 11 18:29:23 jlxb kernel: [ 5318.607232] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001

**Comment by CodeExecution** [comment]
This can be solved by updating the bootloader files (*.dat, *.elf, bootcode.bin). Follow the instructions on the Ubuntu Wiki to solve this: https://wiki.ubuntu.com/ARM/RaspberryPi#Updating_the_Pi_GPU_firmware_and_bootloader_files

**Comment by JLXB** [comment]
Problem solved!  The replacement of the bootloader files was not quite as easy as presented in the link above but I found a work around.  You were right on the mark.

Thanks for your help -You are a Linux gawD!
